### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by pocki** [swdotcom/swdc-visualstudio#43] opened 2021-07-26 08:55 UTC
Please add support for the new Visual Studio 2022. 
Actual it is in Preview but this is good starting point to get extensions ready for release.

**Comment by pocki** [comment] 2021-10-18 15:18
I don't think this PR is working: The version attribute is a range and not an array and also the extension APIs of Visual Studio may have changed.

**Comment by raydixon** [comment] 2021-10-29 22:42
[Closing comment](https://github.com/swdotcom/swdc-visualstudio/pull/45#issuecomment-954762974) from @xavluiz in #45

> Thank you for the PR. The build had issues without having the architecture type specified, but we're going to recreate the visual studio plugin today, based on vs 2022, and should have a version available by next week.

**Comment by xperiandri** [comment] 2021-11-03 17:55
Yep, you need a separate project and separate extension identity in the store to publish 64 bit compatible extension

**Comment by xavluiz** [comment] 2021-11-04 23:31
We've just published v2.6.7 with support for...
- community 17,18 amd64
- community 14,17 x86
- pro 17,18 amd64

The latest version now has "Flow Mode" automations support. The documentation opens our website with more information about this. This version has been updated in all areas (performance, massive cleanup, and websocket support to provide responsive metric updates).

Please let us know what you think. Thank you.

**Comment by xavluiz** [comment] 2021-11-04 23:33
The new logic is no longer in this repo. We will now look for issues in the following:
https://github.com/swdotcom/visualstudio-codetime/issues

Thanks.

**Comment by raydixon** [comment] 2021-11-04 23:48
> The new logic is no longer in this repo. We will now look for issues in the following: https://github.com/swdotcom/visualstudio-codetime/issues
> 
> Thanks.

@xavluiz This URL doesn't work. Is it not public or doesn't exist, yet?

**Comment by xavluiz** [comment] 2021-11-05 14:08
Thank you for the update on the issues link. I'll look into that today.

Thanks.

**Comment by xavluiz** [comment] 2021-11-05 14:20
> Thank you for the update on the issues link. I'll look into that today.
> 
> Thanks.

I've updated the visibility. Thanks again for the reminder.

**Comment by Khaos66** [comment] 2021-11-06 17:14
@xavluiz I've installed the extension for VS2022. But the CodeTime Explorer doesn't change after log in. It still looks like this:
![image](https://user-images.githubusercontent.com/4013009/140618018-dcabbd0b-f3a2-4c1c-aa09-c3b55541f12c.png)
Event after restarting VS.

I choose to log in via GitHub btw.

In your doc this Explorer looks different
![image](https://camo.githubusercontent.com/55e2108a3a82c837015a28d60eaaa29ed16738db2d92a82d141945e9a64f4fb3/68747470733a2f2f6173736574732e736f6674776172652e636f6d2f726561646d652f636f64652d74696d652f76697375616c73747564696f2f66656174757265732d322e352e302e706e67)

**Comment by xavluiz** [comment] 2021-11-08 04:03
Ok, thank you. I'll look into this. We also have a CodeTime channel in the Output. Do you see any errors in that area? Thanks.

**Comment by Khaos66** [comment] 2021-11-08 06:55
Thank you for the info.
Output says:
```
[CodeTime Info 07:52:28 AM] Starting Code Time websocket...
[CodeTime Info 07:52:29 AM] Code Time: Reconnecting the websocket connection, url: wss://api.software.com/websockets
[CodeTime Warning 07:52:29 AM] Code Time: Websocket connection was disconnected
[CodeTime Info 07:52:29 AM] Code Time websocket started.
[CodeTime Info 07:52:30 AM] Code Time: Reconnecting the websocket connection, url: wss://api.software.com/websockets
```

Maybe our firewall is blocking it... I'll have that checked ;)

**Comment by xavluiz** [comment] 2021-11-08 22:39
I see, thank you. I'm unable to currently reproduce the issue but this is good info. Looks like we're missing exposing why the websocket is trying to reconnect, so I'll add that information now and let you know when that is available. Thanks.

**Closed** 2022-02-10 21:08 UTC
